CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(40) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL
);

CREATE TABLE shift_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(60) NOT NULL,
    hours DOUBLE PRECISION NOT NULL,
    color VARCHAR(7) NOT NULL,
    builtin BOOLEAN NOT NULL DEFAULT FALSE,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_shift_types_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_shift_types_user_id ON shift_types(user_id);
CREATE INDEX idx_shift_types_user_name ON shift_types(user_id, name);

CREATE TABLE day_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    entry_date DATE NOT NULL,
    shift_type_id BIGINT,
    overtime_hours DOUBLE PRECISION NOT NULL DEFAULT 0,
    time_off_hours DOUBLE PRECISION NOT NULL DEFAULT 0,
    note TEXT,
    CONSTRAINT uq_day_entries_user_date UNIQUE (user_id, entry_date),
    CONSTRAINT fk_day_entries_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_day_entries_shift_type
        FOREIGN KEY (shift_type_id) REFERENCES shift_types(id)
        ON DELETE SET NULL
);

CREATE INDEX idx_day_entries_user_date ON day_entries(user_id, entry_date);
CREATE INDEX idx_day_entries_shift_type_id ON day_entries(shift_type_id);
