CREATE TABLE day_task_tags (
    task_id BIGINT NOT NULL,
    tag_order INTEGER NOT NULL,
    tag VARCHAR(40) NOT NULL,
    CONSTRAINT pk_day_task_tags PRIMARY KEY (task_id, tag),
    CONSTRAINT fk_day_task_tags_task
        FOREIGN KEY (task_id) REFERENCES day_tasks(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_day_task_tags_tag ON day_task_tags(tag);

UPDATE day_tasks
SET category = NULLIF(lower(trim(category)), '')
WHERE category IS NOT NULL;

CREATE TABLE inbox_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    text VARCHAR(2000) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'OPEN',
    client_operation_id VARCHAR(80),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMP,
    CONSTRAINT fk_inbox_items_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE,
    CONSTRAINT uq_inbox_items_user_client_operation
        UNIQUE (user_id, client_operation_id),
    CONSTRAINT chk_inbox_items_status
        CHECK (status IN ('OPEN', 'ARCHIVED'))
);

CREATE INDEX idx_inbox_items_user_status_created
    ON inbox_items(user_id, status, created_at DESC);
