CREATE TABLE task_subtasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    text VARCHAR(300) NOT NULL,
    done BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_task_subtasks_task
        FOREIGN KEY (task_id) REFERENCES day_tasks(id)
        ON DELETE CASCADE,
    CONSTRAINT chk_task_subtasks_sort_order
        CHECK (sort_order >= 0)
);

CREATE INDEX idx_task_subtasks_task_order
    ON task_subtasks(task_id, sort_order, id);
