CREATE TABLE day_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    task_date DATE NOT NULL,
    text VARCHAR(500) NOT NULL,
    done BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_day_tasks_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_day_tasks_user_date ON day_tasks(user_id, task_date);

CREATE TABLE important_days (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(120) NOT NULL,
    event_date DATE NOT NULL,
    repeat_mode VARCHAR(20) NOT NULL DEFAULT 'NONE',
    color VARCHAR(7) NOT NULL DEFAULT '#F5B841',
    CONSTRAINT fk_important_days_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE,
    CONSTRAINT chk_important_days_repeat_mode
        CHECK (repeat_mode IN ('NONE', 'YEARLY', 'MONTHLY'))
);

CREATE INDEX idx_important_days_user_date ON important_days(user_id, event_date);
