CREATE TABLE day_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    note_date DATE NOT NULL,
    title VARCHAR(200),
    content TEXT NOT NULL DEFAULT '',
    pinned BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    row_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_day_notes_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_day_notes_user_date ON day_notes(user_id, note_date);
CREATE INDEX idx_day_notes_user_date_order ON day_notes(user_id, note_date, pinned DESC, sort_order, id);

-- Preserve every existing single-note day as the first independent note.
INSERT INTO day_notes (user_id, note_date, content, pinned, sort_order, created_at, updated_at)
SELECT d.user_id,
       d.entry_date,
       d.note,
       FALSE,
       0,
       COALESCE(d.updated_at, CURRENT_TIMESTAMP),
       COALESCE(d.updated_at, CURRENT_TIMESTAMP)
FROM day_entries d
WHERE d.note IS NOT NULL
  AND BTRIM(d.note) <> ''
  AND NOT EXISTS (
      SELECT 1 FROM day_notes n
      WHERE n.user_id = d.user_id
        AND n.note_date = d.entry_date
  );
