CREATE TABLE overtime_credits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    work_date DATE NOT NULL,
    time_range VARCHAR(50),
    hours DOUBLE PRECISION NOT NULL,
    reason TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_overtime_credits_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_overtime_credits_user_date ON overtime_credits(user_id, work_date);

CREATE TABLE overtime_usages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    usage_date DATE NOT NULL,
    hours DOUBLE PRECISION NOT NULL,
    reason TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_overtime_usages_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_overtime_usages_user_date ON overtime_usages(user_id, usage_date);

CREATE TABLE overtime_allocations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    credit_id BIGINT NOT NULL,
    usage_id BIGINT NOT NULL,
    hours DOUBLE PRECISION NOT NULL,
    CONSTRAINT fk_overtime_allocations_credit
        FOREIGN KEY (credit_id) REFERENCES overtime_credits(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_overtime_allocations_usage
        FOREIGN KEY (usage_id) REFERENCES overtime_usages(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_overtime_allocations_credit ON overtime_allocations(credit_id);
CREATE INDEX idx_overtime_allocations_usage ON overtime_allocations(usage_id);
